import React, { useCallback, useEffect, useState } from 'react';
import { ChevronLeft, ChevronRight, Plus, Search } from 'lucide-react';
import Card from '../components/ui/Card';
import Button from '../components/ui/Button';
import Input from '../components/ui/Input';
import Modal from '../components/ui/Modal';
import { customerService } from '../services/customerService';
import type { Customer } from '../lib/types';
import { fmtMoney } from '../lib/formatters';

const nameOf = (c: Customer) => c.full_name || [c.first_name, c.last_name].filter(Boolean).join(' ') || 'Sin nombre';
const dateOf = (value?: string | null) => value ? new Date(value).toLocaleDateString('es-BO', { timeZone: 'America/La_Paz' }) : '—';
interface CustomerDetail { customer: Customer; purchase_count: number; total_spent: number; last_purchase: string | null; sales: Array<{ id: string; total: number; sale_date: string; payment_type: string }>; }

export default function CustomersPage() {
  const [query, setQuery] = useState(''); const [page, setPage] = useState(1); const [rows, setRows] = useState<Customer[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState<CustomerDetail | null>(null); const [showCreate, setShowCreate] = useState(false); const [form, setForm] = useState({ first_name: '', last_name: '', phone: '', email: '', instagram: '' });
  const pageSize = 25;
  const load = useCallback(async () => { setLoading(true); try { const result = await customerService.list(query, page, pageSize); setRows(result.customers); setTotal(result.total); } finally { setLoading(false); } }, [query, page]);
  useEffect(() => { const timeout = window.setTimeout(load, 250); return () => window.clearTimeout(timeout); }, [load]);
  const openDetail = async (customer: Customer) => setSelected(await customerService.detail(customer.id) as CustomerDetail);
  const create = async (event: React.FormEvent) => { event.preventDefault(); await customerService.create(form); setShowCreate(false); setForm({ first_name: '', last_name: '', phone: '', email: '', instagram: '' }); await load(); };
  const pages = Math.max(1, Math.ceil(total / pageSize));
  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold text-surface-900">Clientes</h1><p className="text-sm text-surface-500">CRM y compras confirmadas en el POS.</p></div><Button onClick={() => setShowCreate(true)} icon={<Plus className="h-4 w-4" />}>Nuevo cliente</Button></div>
    <Card><div className="mb-5 max-w-lg"><Input value={query} onChange={(e) => { setQuery(e.target.value); setPage(1); }} placeholder="Buscar por nombre, teléfono o código" prefix={<Search className="h-4 w-4" />} /></div>
      <div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b text-left text-surface-500"><tr>{['Código', 'Nombre', 'Teléfono', 'Email', 'Instagram', 'Compras', 'Total gastado', 'Última compra'].map(h => <th key={h} className="px-3 py-3 font-medium">{h}</th>)}</tr></thead><tbody>{rows.map(c => <tr key={c.id} onClick={() => openDetail(c)} className="cursor-pointer border-b last:border-0 hover:bg-surface-50"><td className="px-3 py-3 font-mono text-xs">{c.customer_code}</td><td className="px-3 py-3 font-medium">{nameOf(c)}</td><td className="px-3 py-3">{c.phone || '—'}</td><td className="px-3 py-3">{c.email || '—'}</td><td className="px-3 py-3">{c.instagram || '—'}</td><td className="px-3 py-3">{c.purchase_count || 0}</td><td className="px-3 py-3">Bs. {fmtMoney(c.total_spent || 0)}</td><td className="px-3 py-3">{dateOf(c.last_purchase)}</td></tr>)}{!loading && rows.length === 0 && <tr><td colSpan={8} className="px-3 py-10 text-center text-surface-500">No se encontraron clientes.</td></tr>}</tbody></table></div>
      <div className="mt-5 flex items-center justify-between text-sm text-surface-600"><span>{total} cliente{total === 1 ? '' : 's'}</span><div className="flex items-center gap-2"><Button variant="outline" size="sm" disabled={page <= 1} onClick={() => setPage(page - 1)} icon={<ChevronLeft className="h-4 w-4" />}>Anterior</Button><span>{page} / {pages}</span><Button variant="outline" size="sm" disabled={page >= pages} onClick={() => setPage(page + 1)} iconRight={<ChevronRight className="h-4 w-4" />}>Siguiente</Button></div></div>
    </Card>
    <Modal isOpen={!!selected} onClose={() => setSelected(null)} title="Ficha del cliente" size="lg">{selected && <div className="space-y-5 p-6"><div className="grid grid-cols-2 gap-3 text-sm"><p><b>{selected.customer.customer_code}</b></p><p>Registro: {dateOf(selected.customer.created_at)}</p><p>Teléfono: {selected.customer.phone || '—'}</p><p>Email: {selected.customer.email || '—'}</p><p>Instagram: {selected.customer.instagram || '—'}</p></div><div className="grid grid-cols-3 gap-3"><Card padding="sm"><p className="text-xs text-surface-500">Compras</p><p className="text-lg font-bold">{selected.purchase_count}</p></Card><Card padding="sm"><p className="text-xs text-surface-500">Gasto acumulado</p><p className="text-lg font-bold">Bs. {fmtMoney(selected.total_spent || 0)}</p></Card><Card padding="sm"><p className="text-xs text-surface-500">Última compra</p><p className="text-sm font-bold">{dateOf(selected.last_purchase)}</p></Card></div><div><h3 className="mb-2 font-semibold">Historial de compras</h3>{selected.sales.length ? <div className="space-y-2">{selected.sales.map((sale) => <div key={sale.id} className="flex justify-between rounded border p-3 text-sm"><span>{dateOf(sale.sale_date)} · {sale.payment_type}</span><b>Bs. {fmtMoney(sale.total)}</b></div>)}</div> : <p className="text-sm text-surface-500">Aún no tiene compras asociadas.</p>}</div></div>}</Modal>
    <Modal isOpen={showCreate} onClose={() => setShowCreate(false)} title="Nuevo cliente"><form onSubmit={create} className="space-y-4 p-6"><Input label="Nombre" required value={form.first_name} onChange={e => setForm({ ...form, first_name: e.target.value })}/><Input label="Apellido" value={form.last_name} onChange={e => setForm({ ...form, last_name: e.target.value })}/><Input label="Teléfono" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })}/><Input label="Email" type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })}/><Input label="Instagram" value={form.instagram} onChange={e => setForm({ ...form, instagram: e.target.value })}/><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setShowCreate(false)}>Cancelar</Button><Button type="submit">Crear cliente</Button></div></form></Modal>
  </div>;
}
