import React, { useCallback, useEffect, useState } from 'react';
import { ChevronLeft, ChevronRight, Pencil, Plus, Search, Star } from 'lucide-react';
import Card from '../components/ui/Card';
import Button from '../components/ui/Button';
import Input from '../components/ui/Input';
import Modal from '../components/ui/Modal';
import { customerService } from '../services/customerService';
import type { Customer } from '../lib/types';
import { fmtMoney } from '../lib/formatters';

const nameOf = (c: Customer) => c.full_name || [c.first_name, c.last_name].filter(Boolean).join(' ') || 'Sin nombre';
const dateOf = (value?: string | null) => value ? new Date(value).toLocaleDateString('es-BO', { timeZone: 'America/La_Paz' }) : '—';
interface CustomerDetail { customer: Customer; purchase_count: number; total_spent: number; last_purchase: string | null; sales: Array<{ id: string; total: number; sale_date: string; payment_type: string }>; }
interface LoyaltySummary { enabled: boolean; points_balance: number; lifetime_points_earned: number; lifetime_points_redeemed: number; transactions: Array<{ id: string; sale_id?: string | null; type: string; points: number; balance_after: number; reason: string; created_at: string }>; }

export default function CustomersPage() {
  const [query, setQuery] = useState(''); const [page, setPage] = useState(1); const [rows, setRows] = useState<Customer[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState<CustomerDetail | null>(null); const [showCreate, setShowCreate] = useState(false); const [editing, setEditing] = useState(false); const [showPoints, setShowPoints] = useState(false); const [loyalty, setLoyalty] = useState<LoyaltySummary | null>(null); const [editError, setEditError] = useState(''); const [saving, setSaving] = useState(false); const [form, setForm] = useState({ first_name: '', last_name: '', phone: '', email: '', instagram: '' });
  const pageSize = 25;
  const load = useCallback(async () => { setLoading(true); try { const result = await customerService.list(query, page, pageSize); setRows(result.customers); setTotal(result.total); } finally { setLoading(false); } }, [query, page]);
  useEffect(() => { const timeout = window.setTimeout(load, 250); return () => window.clearTimeout(timeout); }, [load]);
  const openDetail = async (customer: Customer) => { const [detail, points] = await Promise.all([customerService.detail(customer.id), customerService.loyalty(customer.id).catch(() => null)]); const value = detail as CustomerDetail; setSelected(value); setLoyalty(points as LoyaltySummary | null); };
  const startEdit = () => { if (!selected) return; setEditError(''); setForm({ first_name: selected.customer.first_name || '', last_name: selected.customer.last_name || '', phone: selected.customer.phone || '', email: selected.customer.email || '', instagram: selected.customer.instagram || '' }); setEditing(true); };
  const saveEdit = async (event: React.FormEvent) => { event.preventDefault(); if (!selected) return; setSaving(true); setEditError(''); try { const updated = await customerService.update(selected.customer.id, { ...form, active: !selected.customer.deactivated_at }); setSelected({ ...selected, customer: updated }); setEditing(false); await load(); } catch (error) { setEditError(error instanceof Error ? error.message : 'No se pudo actualizar el cliente'); } finally { setSaving(false); } };
  const adjustPoints = async () => { if (!selected) return; const rawPoints = window.prompt('Puntos a ajustar. Usa negativo para restar:'); const points = Number(rawPoints); if (!Number.isInteger(points) || points === 0) return; const reason = window.prompt('Motivo obligatorio:'); if (!reason?.trim()) return; try { const result = await customerService.adjustPoints(selected.customer.id, points, reason); setLoyalty(current => current ? { ...current, points_balance: result.points_balance, lifetime_points_earned: current.lifetime_points_earned + Math.max(points, 0), lifetime_points_redeemed: current.lifetime_points_redeemed + Math.max(-points, 0), transactions: current.transactions } : current); } catch (error) { window.alert(error instanceof Error ? error.message : 'No se pudo ajustar puntos'); } };
  const create = async (event: React.FormEvent) => { event.preventDefault(); await customerService.create(form); setShowCreate(false); setForm({ first_name: '', last_name: '', phone: '', email: '', instagram: '' }); await load(); };
  const pages = Math.max(1, Math.ceil(total / pageSize));
  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold text-surface-900">Clientes</h1><p className="text-sm text-surface-500">CRM y compras confirmadas en el POS.</p></div><Button onClick={() => setShowCreate(true)} icon={<Plus className="h-4 w-4" />}>Nuevo cliente</Button></div>
    <Card><div className="mb-5 max-w-lg"><Input value={query} onChange={(e) => { setQuery(e.target.value); setPage(1); }} placeholder="Buscar por nombre, teléfono o código" prefix={<Search className="h-4 w-4" />} /></div>
      <div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b text-left text-surface-500"><tr>{['Código', 'Nombre', 'Teléfono', 'Email', 'Instagram', 'Compras', 'Total gastado', 'Última compra'].map(h => <th key={h} className="px-3 py-3 font-medium">{h}</th>)}</tr></thead><tbody>{rows.map(c => <tr key={c.id} onClick={() => openDetail(c)} className="cursor-pointer border-b last:border-0 hover:bg-surface-50"><td className="px-3 py-3 font-mono text-xs">{c.customer_code}</td><td className="px-3 py-3 font-medium">{nameOf(c)}</td><td className="px-3 py-3">{c.phone || '—'}</td><td className="px-3 py-3">{c.email || '—'}</td><td className="px-3 py-3">{c.instagram || '—'}</td><td className="px-3 py-3">{c.purchase_count || 0}</td><td className="px-3 py-3">Bs. {fmtMoney(c.total_spent || 0)}</td><td className="px-3 py-3">{dateOf(c.last_purchase)}</td></tr>)}{!loading && rows.length === 0 && <tr><td colSpan={8} className="px-3 py-10 text-center text-surface-500">No se encontraron clientes.</td></tr>}</tbody></table></div>
      <div className="mt-5 flex items-center justify-between text-sm text-surface-600"><span>{total} cliente{total === 1 ? '' : 's'}</span><div className="flex items-center gap-2"><Button variant="outline" size="sm" disabled={page <= 1} onClick={() => setPage(page - 1)} icon={<ChevronLeft className="h-4 w-4" />}>Anterior</Button><span>{page} / {pages}</span><Button variant="outline" size="sm" disabled={page >= pages} onClick={() => setPage(page + 1)} iconRight={<ChevronRight className="h-4 w-4" />}>Siguiente</Button></div></div>
    </Card>
    <Modal isOpen={!!selected} onClose={() => setSelected(null)} title="Ficha del cliente" size="lg">{selected && <div className="space-y-5 p-6"><div className="flex items-start justify-between gap-4"><div><p className="font-mono text-lg font-bold">{selected.customer.customer_code}</p><p className="mt-1 text-xs text-surface-500">Registro: {dateOf(selected.customer.created_at)} · {selected.customer.deactivated_at ? 'Inactivo' : 'Activo'}</p></div><Button size="sm" variant="outline" onClick={startEdit} icon={<Pencil className="h-3.5 w-3.5"/>}>Editar cliente</Button></div><div className="grid gap-3 text-sm sm:grid-cols-2"><p><b>Nombre:</b> {nameOf(selected.customer)}</p><p><b>Teléfono:</b> {selected.customer.phone || '—'}</p><p><b>Email:</b> {selected.customer.email || '—'}</p><p><b>Instagram:</b> {selected.customer.instagram || '—'}</p></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-3"><Card padding="sm"><p className="text-xs text-surface-500">Compras</p><p className="text-lg font-bold">{selected.purchase_count}</p></Card><Card padding="sm"><p className="text-xs text-surface-500">Gasto acumulado</p><p className="text-lg font-bold">Bs. {fmtMoney(selected.total_spent || 0)}</p></Card><Card padding="sm"><p className="text-xs text-surface-500">Puntos</p><p className="text-lg font-bold">{loyalty?.enabled ? loyalty.points_balance : '—'}</p></Card></div>{loyalty?.enabled && <div className="rounded-xl border border-brand-100 bg-brand-50/50 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Star className="h-4 w-4 text-brand-600"/><h3 className="font-semibold">Fidelidad</h3></div><p className="mt-1 text-xs text-surface-500">Ganados: {loyalty.lifetime_points_earned} · Usados: {loyalty.lifetime_points_redeemed}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => setShowPoints(true)}>Ver historial</Button><Button size="sm" onClick={adjustPoints}>Ajustar puntos</Button></div></div></div>}<div><h3 className="mb-2 font-semibold">Historial de compras</h3>{selected.sales.length ? <div className="space-y-2">{selected.sales.map((sale) => <div key={sale.id} className="flex justify-between rounded border p-3 text-sm"><span>{dateOf(sale.sale_date)} · {sale.payment_type}</span><b>Bs. {fmtMoney(sale.total)}</b></div>)}</div> : <p className="text-sm text-surface-500">Aún no tiene compras asociadas.</p>}</div></div>}</Modal>
    <Modal isOpen={editing} onClose={() => setEditing(false)} title="Editar cliente" description="El código PASS y el vínculo de Auth no se pueden editar."><form onSubmit={saveEdit} className="space-y-4 p-6"><div className="grid gap-4 sm:grid-cols-2"><Input label="Nombre" required value={form.first_name} onChange={e => setForm({ ...form, first_name: e.target.value })}/><Input label="Apellido" value={form.last_name} onChange={e => setForm({ ...form, last_name: e.target.value })}/></div><Input label="Teléfono" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })}/><Input label="Email" type="email" disabled={!!selected?.customer.auth_user_id} hint={selected?.customer.auth_user_id ? 'Cliente vinculado: el email se protege para no romper Auth.' : undefined} value={form.email} onChange={e => setForm({ ...form, email: e.target.value })}/><Input label="Instagram" value={form.instagram} onChange={e => setForm({ ...form, instagram: e.target.value })}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!selected?.customer.deactivated_at} onChange={e => setSelected(selected ? { ...selected, customer: { ...selected.customer, deactivated_at: e.target.checked ? null : new Date().toISOString() } } : selected)}/> Cliente activo</label>{editError && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{editError}</p>}<div className="flex justify-end gap-2 border-t border-surface-100 pt-4"><Button type="button" variant="outline" onClick={() => setEditing(false)}>Cancelar</Button><Button type="submit" disabled={saving}>{saving ? 'Guardando…' : 'Guardar cambios'}</Button></div></form></Modal>
    <Modal isOpen={showPoints} onClose={() => setShowPoints(false)} title="Historial de puntos" size="lg">{loyalty && <div className="p-6"><div className="mb-5 grid grid-cols-3 gap-3"><Card padding="sm"><p className="text-xs text-surface-500">Saldo</p><p className="text-lg font-bold">{loyalty.points_balance}</p></Card><Card padding="sm"><p className="text-xs text-surface-500">Ganados</p><p className="text-lg font-bold">{loyalty.lifetime_points_earned}</p></Card><Card padding="sm"><p className="text-xs text-surface-500">Usados</p><p className="text-lg font-bold">{loyalty.lifetime_points_redeemed}</p></Card></div>{loyalty.transactions.length ? <div className="divide-y">{loyalty.transactions.map(item => <div key={item.id} className="flex items-center justify-between gap-3 py-3 text-sm"><div><p className="font-medium">{item.reason}</p><p className="text-xs text-surface-500">{dateOf(item.created_at)} · {item.sale_id ? 'Compra' : 'Ajuste'}</p></div><div className="text-right"><p className={item.points > 0 ? 'font-bold text-emerald-700' : 'font-bold text-red-700'}>{item.points > 0 ? '+' : ''}{item.points} pts</p><p className="text-xs text-surface-500">Saldo {item.balance_after}</p></div></div>)}</div> : <p className="text-sm text-surface-500">Todavía no hay movimientos.</p>}</div>}</Modal>
    <Modal isOpen={showCreate} onClose={() => setShowCreate(false)} title="Nuevo cliente"><form onSubmit={create} className="space-y-4 p-6"><Input label="Nombre" required value={form.first_name} onChange={e => setForm({ ...form, first_name: e.target.value })}/><Input label="Apellido" value={form.last_name} onChange={e => setForm({ ...form, last_name: e.target.value })}/><Input label="Teléfono" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })}/><Input label="Email" type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })}/><Input label="Instagram" value={form.instagram} onChange={e => setForm({ ...form, instagram: e.target.value })}/><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setShowCreate(false)}>Cancelar</Button><Button type="submit">Crear cliente</Button></div></form></Modal>
  </div>;
}
